dist: trusty

language: php

php:
  # using major version aliases
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
- |
    echo "Updating Composer"
    rm $TRAVIS_BUILD_DIR/composer.json
    rm $TRAVIS_BUILD_DIR/composer.lock
    composer self-update
    composer -n init
    echo

- |
    echo "Installing Parallel Lint"
    composer -n require jakub-onderka/php-parallel-lint ^0
    composer -n require jakub-onderka/php-console-highlighter ^0
    echo

script:
  - |
    # ./bin/phplint ./ --no-cache
    echo "Checking PHP syntax errors"
    # Ensure we catch errors
    set -e
    #parallel-lint --exclude htdocs/includes --blame .
    ./bin/parallel-lint --exclude htdocs/includes/sabre --exclude htdocs/includes/phpoffice/phpexcel/Classes/PHPExcel/Shared --exclude htdocs/includes/phpoffice/PhpSpreadsheet --exclude htdocs/includes/sebastian --exclude htdocs/includes/squizlabs/php_codesniffer/tests --exclude htdocs/includes/jakub-onderka/php-parallel-lint/tests --exclude htdocs/includes/mike42/escpos-php/example --exclude htdocs/includes/phpunit/php-token-stream/tests --exclude htdocs/includes/composer/autoload_static.php --blame .
    set +e
    echo

matrix:
  fast_finish: true